import type { SavedMedication } from "@/lib/seed-medications";

/**
 * Jade’s one-tap Quick Setup bundle (not used as the default app seed).
 * Keep out of public forks by deleting this module if you ship a generic build.
 */
export const JADE_QUICK_SETUP_MEDICATIONS: SavedMedication[] = [
  {
    id: "jade-gleevec",
    name: "Gleevec",
    pathway: "CYP3A4",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role:
      "CYP3A4 substrate (imatinib) — sensitive to strong inhibitors",
    doseLabel: "100mg · 2× daily",
    frequencyHint: "2x",
  },
  {
    id: "jade-buspirone",
    name: "Buspirone",
    pathway: "CYP3A4",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role: "CYP3A4 substrate",
    has_dizziness_side_effect: true,
    doseLabel: "30mg · 2× daily",
    frequencyHint: "2x",
  },
  {
    id: "jade-pregabalin",
    name: "Pregabalin",
    pathway: "Renal (Kidneys)",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Renal clearance",
    has_dizziness_side_effect: true,
    doseLabel: "75mg · 2× daily",
    frequencyHint: "2x",
  },
  {
    id: "jade-estradiol",
    name: "Estradiol",
    pathway: "Other / Unknown",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Hormone / varied metabolism",
    doseLabel: "2mg · 1× daily",
    frequencyHint: "1x",
  },
  {
    id: "jade-trazodone",
    name: "Trazodone",
    pathway: "CYP3A4",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role: "CYP3A4 substrate",
    has_orthostatic_hypotension: true,
    doseLabel: "100mg · 1× daily",
    frequencyHint: "1x",
  },
  {
    id: "jade-magnesium",
    name: "Magnesium",
    pathway: "Other / Unknown",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Absorption / renal excretion of Mg²⁺",
    doseLabel: "1000mg · 1× daily",
    frequencyHint: "1x",
  },
  {
    id: "jade-latuda",
    name: "Latuda",
    pathway: "CYP3A4",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role:
      "CYP3A4 substrate (lurasidone) — sensitive to strong inhibitors",
    has_orthostatic_hypotension: true,
    doseLabel: "120mg · 1× daily",
    frequencyHint: "1x",
  },
  {
    id: "jade-midodrine",
    name: "Midodrine",
    pathway: "Other / Unknown",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Prodrug; orthostatic support",
    has_orthostatic_hypotension: false,
    doseLabel: "10mg · 3× daily",
    frequencyHint: "3x",
  },
  {
    id: "jade-duloxetine",
    name: "Duloxetine",
    pathway: "CYP2D6",
    is_inhibitor: true,
    is_substrate: false,
    pathway_role: "CYP2D6 inhibitor",
    has_orthostatic_hypotension: true,
    doseLabel: "60mg · 1× daily",
    frequencyHint: "1x",
  },
  {
    id: "jade-methylphenidate",
    name: "Methylphenidate",
    pathway: "CYP2D6",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role: "CYP2D6 substrate",
    has_dizziness_side_effect: true,
    doseLabel: "10mg · 3× daily",
    frequencyHint: "3x",
  },
  {
    id: "jade-thermotabs",
    name: "Thermotabs",
    pathway: "Other / Unknown",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Electrolyte / sodium chloride supplement",
    doseLabel: "360mg · 2× daily",
    frequencyHint: "2x",
  },
  {
    id: "jade-methocarbamol",
    name: "Methocarbamol",
    pathway: "Other / Unknown",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "Muscle relaxant",
    has_dizziness_side_effect: true,
    doseLabel: "750mg · as needed",
    frequencyHint: "prn",
  },
  {
    id: "jade-lorazepam",
    name: "Lorazepam",
    pathway: "UGT1A1",
    is_inhibitor: false,
    is_substrate: false,
    pathway_role: "UGT conjugation",
    has_orthostatic_hypotension: true,
    doseLabel: "0.5mg · as needed",
    frequencyHint: "prn",
  },
  {
    id: "jade-ondansetron",
    name: "Ondansetron",
    pathway: "CYP3A4",
    is_inhibitor: false,
    is_substrate: true,
    pathway_role: "CYP3A4 / CYP1A2 substrate",
    doseLabel: "4mg",
    frequencyHint: "prn",
  },
];
